name: 02 â€“ Workflow Events

on:
  push:
  pull_request:
  schedule:
    - cron: "5 * * * *"
  workflow_dispatch:

jobs:
  echo:
    name: "zobrancz co mnie ztriggerowalo ${{ github.event_name}} ${GITHUB_EVENT_NAME}"
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger ${{ github.event_name}} ${GITHUB_EVENT_NAME}
        run: |
          echo "Event name: ${{ github.event_name}} ${GITHUB_EVENT_NAME}"