name: 04 - Workflow uses actions

on:
  workflow_dispatch:

jobs:
  build:
    name: Build and Test with Node.js
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./CWIECZENIA/04
    steps:
      - name: use actions/checkout action
        uses: actions/checkout@v5
      - name: pokaz zawartosc katalogu
        run: |
          ls -la
        
